build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true

complexity:
  active: true
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 9
    ignoreDefaultParameters: true
    ignoreDataClasses: true
    ignoreAnnotatedParameter: []

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: false

style:
  active: true
  MagicNumber:
    active: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '10'
      - '100'
      - '1000'
    ignoreHashCodeFunction: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignorePropertyDeclaration: true
    ignoreLocalVariableDeclaration: false
  MaxLineLength:
    active: true
    maxLineLength: 140
    excludePackageStatements: true
    excludeImportStatements: true

empty-blocks:
  active: true

formatting:
  active: true
  autoCorrect: true
  NoWildcardImports:
    active: true
  FinalNewline:
    active: true
  Indentation:
    active: true
  MaximumLineLength:
    active: true
    maxLineLength: 140
  SpacingAroundComma:
    active: true

